# config_dev.yml
# This file is used to configure the service locally for development
debug: true
host: "localhost"
api_keys: 
  - "shuffle2024"
  - "api_key_1"
  - "api_key_2"

# Runner Configuration
# The max. count of runners for rest_runner is 10
# The max. count of runners for stream_runner is 1
# Example:
# identifier:
#   device: "cpu" or "cuda"
#   model: model_name
#   compute_type: "int8" (cpu), "float16" (cuda), "int8_float16" (cuda)

stream_runner:
  -   device: cpu
      model: tiny
      compute_type: int8

rest_runner:
  -   device: cpu
      model: tiny
      compute_type: int8
  -   device: cpu
      model: tiny
      compute_type: int8
