# config.yml
# This file is used to configure the service for a production stage in a Docker container
debug: True
host: "0.0.0.0"
api_keys: 
  - "shuffle2024"
  - "api_key_1"
  - "api_key_2"

# Runner Configuration
# The max. count of runners for rest_runner is 10
# The max. count of runners for stream_runner is 1
# Example:
# identifier:
#   device: "cpu" or "cuda"
#   model: model_name
#   compute_type: "int8" (cpu), "float16" (cuda), "int8_float16" (cuda)

stream_devices:
  cpu:
    active: True
    model: tiny
    threads: 1
    num_workers: 2
    worker_seats: 1

  gpu:
    active: False
    model: large
    device_ids: [0]
    worker_seats: 1

rest_runner:
  -   device: cpu
      model: tiny
      compute_type: int8
      device_index: [0]
      num_workers: 1
      cpu_threads: 4
