version: '3'

services:
  asr-api:
    build: .
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data/audio_files:/asr-api/data/audio_files
      - ./data/status:/asr-api/data/status
    ports:
      - "8393:8393"
      - "8394:8394"
