version: '3'

volumes:
  audio_files:
  transcripts:
  status:


services:
  api:
    image: ghcr.io/shuffle-project/asr-api-api:deploy
    container_name: asr-api-api
    volumes:
      - audio_files:/data/audio_files
      - transcripts:/data/transcripts
      - status:/data/status
    ports:
      - "8393:8393"
      - "8394:8394"
      
  whispercpp_runner:
    image: ghcr.io/shuffle-project/asr-api-whispercpp_runner:deploy
    container_name: asr-api-whispercpp_runner
    volumes:
      - audio_files:/data/audio_files
      - transcripts:/data/transcripts
      - status:/data/status
    depends_on:
      - api
