version: '3'

services:
  asr-api:
    image: ghcr.io/shuffle-project/asr-api:main
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data:/asr-api/data
      - ./config.yml:/asr-api/config.yml
    ports:
      - "8393:8393"
      - "8394:8394"