version: '3'

services:
  asr-api:
    build: .
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data/audio_files:/asr-api/data/audio_files
      - ./data/status:/asr-api/data/status
    environment:
      - ENVIRONMENT=production
      - PORT=8393
      - WEBSOCKET_PORT=8394
      - HOST=0.0.0.0
      - API_KEY=shuffle2024
      - DEBUG=True
      - MODEL=tiny
      - WHISPER_MODELS=["tiny", "medium", "large"]
      - AUDIO_FILE_PATH=/data/audio_files
      - STATUS_PATH=/data/status
      - AUDIO_FILE_FORMAT=.wav
    ports:
      - "8393:8393"
      - "8394:8394"