version: '3'

services:
  asr-api:
    build: .
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data:/asr-api/data
      - ./config.dev.yml:/asr-api/config.yml
    ports:
      - "8393:8393"
      - "8394:8394"
