version: '3'

services:
  asr-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data:/asr-api/data
      - ./config.yml:/asr-api/config.yml
    ports:
      - "8393:8393"
      - "8394:8394"
    
    # Use the following part to utilize GPU 
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]