version: '3'

services:
  asr-api:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data:/asr-api/data
      - ./config.gpu.yml:/asr-api/config.yml
    ports:
      - "8393:8393"
      - "8394:8394"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]