version: '3'

services:
  asr-api:
    image: ghcr.io/shuffle-project/asr-api:main
    container_name: asr-api
    volumes:
      - ./models:/asr-api/models
      - ./data/audio_files:/asr-api/data/audio_files
      - ./data/status:/asr-api/data/status
    environment:
      - PORT=8393
      - WEBSOCKET_PORT=8394
      - HOST=0.0.0.0
      - API_KEY=shuffle2024
      - DEBUG=True
      - UNLAOD_REST_MODELS_SCHEDULE=10
      - MODEL_PATH=/models/
      - STREAM_MODEL=tiny
      - AUDIO_FILE_PATH=/data/audio_files/
      - STATUS_PATH=/data/status/
      - AUDIO_FILE_FORMAT=.wav
      - MAX_OLD_STATUS_FILES=1000
      - CLEAN_UP_SCHEDULE=120
    ports:
      - "8393:8393"
      - "8394:8394"